apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bugsink.fullname" . }}
  labels:
    {{- include "bugsink.labels" . | nindent 4 }}
data:
  ALLOWED_HOSTS: "*"
  {{- with .Values.baseUrl }}
  BASE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.timezone }}
  TIME_ZONE: {{ . | quote }}
  {{- end }}
  {{- if .Values.smtp.enabled }}
  EMAIL_HOST: {{ .Values.smtp.host | quote }}
  {{- with .Values.smtp.port }}
  EMAIL_PORT: {{ . | quote }}
  {{- end }}
  EMAIL_USE_TLS: {{ ternary "True" "False" .Values.smtp.useTls | quote }}
  EMAIL_USE_SSL: {{ ternary "True" "False" .Values.smtp.useSsl | quote }}
  {{- with .Values.smtp.timeout }}
  EMAIL_TIMEOUT: {{ . | quote }}
  {{- end }}
  {{- with .Values.smtp.defaultFrom }}
  DEFAULT_FROM_EMAIL: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- range $extraConfigKey, $extraConfigValue := .Values.extraEnv.configs }}
  {{ $extraConfigKey }}: {{ $extraConfigValue | quote }}
  {{- end }}
