{{- if (include "bugsink.secret.create" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bugsink.fullname" . }}
  labels:
    {{- include "bugsink.labels" . | nindent 4 }}
stringData:
  {{- if not .Values.secretKey.existingSecret }}
  SECRET_KEY: {{ include "bugsink.secretKey" . | quote }}
  {{- end }}
  {{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
  EMAIL_HOST_USER: {{ .Values.smtp.username | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if not .Values.admin.existingSecret }}
  CREATE_SUPERUSER: {{ include "bugsink.admin.auth" . | quote }}
  {{- end }}
  {{- range $extraSecretKey, $extraSecretValue := .Values.extraEnv.secrets }}
  {{ $extraSecretKey }}: {{ $extraSecretValue | quote }}
  {{- end }}
{{- end }}
