name: Release Helm Charts

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    name: Build and package Helm charts
    permissions:
      contents: read
    env:
      GITHUB_PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v${{ vars.HELM_VERSION }}

      - name: Package charts
        run: |
          mkdir -p packaged_charts
          for dir in charts/*; do
            if [ -f "$dir/Chart.yaml" ]; then
              helm dependency update "$dir" || true
              helm package "$dir" -d packaged_charts
            fi
          done

      - name: Generate index.yaml
        run: |
          curl -fL ${{ env.GITHUB_PAGES_URL }}/index.yaml -o packaged_charts/index.yaml || true
          if [ -f packaged_charts/index.yaml ]; then
            helm repo index packaged_charts --url ${{ env.GITHUB_PAGES_URL }} --merge packaged_charts/index.yaml
          else
            helm repo index packaged_charts --url ${{ env.GITHUB_PAGES_URL }}
          fi

      - name: Upload packaged charts artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packaged_charts

  deploy:
    needs: build
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
