name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    name: Lint Helm charts
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v${{ vars.HELM_VERSION }}

      - name: Lint charts
        run: |
          helm lint charts/*

  release:
    needs: lint
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    name: Release Helm Charts
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v${{ vars.HELM_VERSION }}

      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release charts
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
