name: Test Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Helm charts
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.4

      - name: Lint charts
        run: |
          for dir in charts/*; do
            if [ -f "$dir/Chart.yaml" ]; then
              echo "Linting chart: $dir"
              helm dependency update "$dir" || true
              helm lint "$dir"
            fi
          done
