name: Test Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    name: Lint Helm charts
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v${{ vars.HELM_VERSION }}

      - name: Lint charts
        run: |
          helm lint charts/*
